Repository openshift/origin-web-common, pull requests merged in 2018-02, with the labels that each got.

#301 Add utilities for comparing versions
  bower.json
  dist/origin-web-common-services.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  package-lock.json
  package.json
  src/services/versionsService.js
  test/karma.conf.js
  test/spec/services/versionsServiceSpec.js
Labels: size/XXL

#302 Bump version to 3.9.0-alpha.12
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/M

#303 Update npm dependencies to match origin-web-console repo
  .travis.yml
  Gruntfile.js
  dist/origin-web-common.min.js
  package-lock.json
  package.json
Labels: lgtm, size/XXL

#304 Avoid runtime errors when requested resource doesn't exist
  dist/origin-web-common-services.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  src/services/dataService.js
Labels: size/L

#305 Bump version to 3.9.0-alpha.13
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#306 Bump dependencies
  package-lock.json
  package.json
Labels: size/XXL

#307 Always return false in canI checks where resource is not set
  dist/origin-web-common-services.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  src/services/authorizationService.js
Labels: lgtm, size/S

#309 Bump version to 3.9.0-alpha.14
  bower.json
  package-lock.json
  package.json
Labels: size/XS
