Repository openshift/origin-web-common, pull requests merged in 2018-03, with the labels that each got.

#310 Bump version to 3.9.0
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#311 Bug 1551904 - Deduplicate NetworkPolicy from availableKinds
  .gitignore
  dist/origin-web-common-services.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  src/constants/apiDedupe.js
  test/karma.conf.js
  test/spec/services/apiServiceSpec.js
Labels: lgtm, size/S

#313 Bump version to 3.9.1
  bower.json
  package-lock.json
  package.json
Labels: size/XS

#314 Add preferred version for daemon sets
  dist/origin-web-common-services.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  src/constants/apiPreferredVersions.js
Labels: lgtm, size/M

#315 Bump version to 3.10.0-alpha.0
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/XS

#318 Change project deletion confirmation message
  dist/origin-web-common-ui.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  dist/scripts/templates.js
  src/components/delete-project/delete-project-modal.html
Labels: size/S

#317 Bug 1449038 - Add a simple weighted search to KeywordService
  dist/origin-web-common-services.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  src/services/keyword.js
  test/spec/services/keywordServiceSpec.js
Labels: lgtm, size/L

#316 Remove hawtio dependency
  .jshintrc
  Gruntfile.js
  bower.json
  dist/origin-web-common-services.js
  dist/origin-web-common-ui.js
  dist/origin-web-common.js
  dist/origin-web-common.min.js
  src/openshiftCommonServices.module.js
  src/openshiftCommonUI.module.js
  src/pluginLoader.js
  test/.jshintrc
  test/karma.conf.js
Labels: size/XXL

#319 Bump version to 3.10.0-alpha.1
  bower.json
  package-lock.json
  package.json
Labels: lgtm, size/XS
